# SonarCloud Project Configuration
sonar.projectKey=spa173_contex360.fronted
sonar.organization=spa173
sonar.host.url=https://sonarcloud.io

# Source and Test Directories
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.{test,spec}.{js,ts}
sonar.exclusions=**/node_modules/**,**/dist/**,src/test/**,eslint.config.js,vitest.config.js,vite.config.js,postcss.config.js,tailwind.config.js

# Code Coverage Reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info
